---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - SAUCE_USERNAME="aesopwolf"
  - SAUCE_ACCESS_KEY="2d7d01c9-eb84-464e-888b-d5f12e7e5c12"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test

before_script:
  - ember sauce:connect

after_script:
  - ember sauce:disconnect
